### ISSUE TITLE
LNC logo update request

### ISSUE THREAD

**Issue by almal** [datacult/near-stats#19]
Awesome  job!

Please update Learn NEAR Club logo

https://learnnear.club/brand-logos/

Thank you!

**Comment by neil-oliver** [comment]
Hi @almal, 
All app data, including logos are handled through the [NEAR Ecosystem Repo](https://github.com/near/ecosystem). Please open and issue, or if possible, a PR with the update for the logo. Thanks!

**Comment by almal** [comment]
Oh, cool, makes sense!
thank you

**Comment by almal** [comment]
It seems there is an issue:
stat uses https://github.com/near/ecosystem/raw/main/img/learn-near.png
logo link at repo  https://github.com/near/ecosystem/blob/main/img/learn-near-logo.png

**Comment by neil-oliver** [comment]
This will likely be due to the caching. The data is updated every 24 hours and the ecosystem data was only updated 2 hours ago.

**Comment by almal** [comment]
Got it, thank you!
Awesome imitative!
LMK if you need any help with promo, etc.
