### ISSUE TITLE
Missing Paras and AstroDAO

### ISSUE THREAD

**Issue by starpause** [datacult/near-stats#5]
Checking https://near-stats-67l44236iq-uc.a.run.app/

I don't see https://paras.id/ or https://astrodao.com/ 

AstroDAO is similar to Mintbase, a contract launcher, so all of it's contracts sit under `sputnik-dao.near`

Paras contracts are `x.paras.near` and `marketplace.paras.near`

**Comment by neil-oliver** [comment]
Hi @starpause, The NEAR Stats project does not directly handle to the contracts data; this is all managed through the [NEAR Ecosystems Repo](https://github.com/near/ecosystem). If you can open a PR there with the updated data, this will start to populate through to the [NEAR Analytics](https://github.com/near/near-analytics/) project. This is where we pull our data for the dashboard.
